FROM golang:1.22-bullseye AS builder

WORKDIR /src/

# gcc is required by go-sqlite3 (CGO)
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO_ENABLED=1 is required for go-sqlite3
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -mod=readonly -o /app/webapi ./cmd/webapi


FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/webapi /app/webapi

WORKDIR /app

EXPOSE 3000

CMD ["/app/webapi"]
